version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_DEBUG=False
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=zhunshi_user
      - MYSQL_PASSWORD=zhunshi_password
      - MYSQL_DATABASE=zhunshi_prod
    depends_on:
      - db
    restart: always

  db:
    image: mysql:8.0
    volumes:
      - mysql_data_prod:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=zhunshi_prod
      - MYSQL_USER=zhunshi_user
      - MYSQL_PASSWORD=zhunshi_password
    ports:
      - "3306:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always

volumes:
  mysql_data_prod: 