version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - app_logs_dev:/app/logs
    environment:
      - FLASK_DEBUG=True
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=zhunshi_user
      - MYSQL_PASSWORD=zhunshi_password
      - MYSQL_DATABASE=zhunshi_dev
    command: >
      bash -c "mkdir -p /app/logs/app &&
               touch /app/logs/app/error.log &&
               touch /app/logs/app/access.log &&
               chmod -R 777 /app/logs &&
               flask run --host=0.0.0.0"
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:8.0
    volumes:
      - mysql_data_dev:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=zhunshi_dev
      - MYSQL_USER=zhunshi_user
      - MYSQL_PASSWORD=zhunshi_password
    ports:
      - "3307:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: unless-stopped

volumes:
  mysql_data_dev:
  app_logs_dev: 