version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    expose:
      - "5000"
    environment:
      - FLASK_DEBUG=False
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=zhunshi_user
      - MYSQL_PASSWORD=zhunshi_password
      - MYSQL_DATABASE=zhunshi_prod
    volumes:
      - app_logs:/app/logs
    command: >
      bash -c "mkdir -p /app/logs/app &&
               touch /app/logs/app/error.log &&
               touch /app/logs/app/access.log &&
               chmod -R 777 /app/logs &&
               sleep 10 &&
               gunicorn --config gunicorn.conf.py wsgi:app"
    depends_on:
      db:
        condition: service_healthy
    restart: always

  nginx:
    image: nginx:1.26
    ports:
      - "80:80"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./app/static:/app/static
      - nginx_logs:/var/log/nginx
    depends_on:
      - web
    restart: always

  db:
    image: mysql:8.0
    volumes:
      - mysql_data_prod:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=zhunshi_prod
      - MYSQL_USER=zhunshi_user
      - MYSQL_PASSWORD=zhunshi_password
    ports:
      - "3306:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "zhunshi_user", "-pzhunshi_password"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  mysql_data_prod:
  app_logs:
  nginx_logs: 