services:
  # Web服务配置
  - type: web
    name: pyreminder
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true  # 自动生成随机密钥
      - key: FLASK_DEBUG
        value: "False"
      - key: NOTIFICATION_TOKEN
        sync: false  # 允许手动设置
      - key: TIMEZONE
        value: "Asia/Shanghai"  # 使用中国时区
      - key: REDIS_DB
        value: "0"
      - key: REDIS_HOST
        value: "amused-bream-11167.upstash.io"
      - key: REDIS_PORT
        value: "6379"
      - key: REDIS_PASSWORD
        sync: false  # 需要手动设置
      - key: REDIS_SSL
        value: "True" 